name: Build & Deploy

on:
  push:
    branches: [ "production" ]

  pull_request:
    branches: [ "production" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            app/
            aptain-definition
          outPath: deploy.tar

      # - uses: a7ul/tar-action@v1.1.0
      #   with:
      #     command: c
      #     cwd: "./"
      #     files: |
      #       app/
      #       frontend/dist/
      #       captain-definition
      #     outPath: deploy.tar


  
      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'